services:
  api:
    build:
      context: ./
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - internal
    restart: always

  redis:
    image: redis:7.2.4-alpine    
    networks:
      - internal
    restart: always

networks:
  internal:
