services:
  api:
    build:
      context: ./
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - internal
    restart: always

  redis:
    image: redis:7.2.4-alpine    
    networks:
      - internal
    restart: always

  nginx:
    image: nginx:1.25.4-alpine
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=mail.sistemagtf.com.br
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mail.sistemagtf.com.br
    networks:
      - proxy-nginx
      - internal
    restart: always

networks:
  proxy-nginx:
    external: true
  internal:
